### ISSUE TITLE
Fails (HTTP 401) if Basic Authentication required to access URL's in XSD

### ISSUE THREAD

**Issue by ruiper** [NetSPI/Wsdler#4]
Below is stack trace obtained from verbose version of wslder

Get Error: Can’t parse WSDL.
java.exe -jar c:\Software\Sectools\burpsuite_pro_v1.6.39.jar 
org.reficio.ws.SoapBuilderException: WSDLException (at /definitions/types/xsd:schema[2]): faultCode=OTHER_ERROR: An error occurred trying to resolve schema referenced at 'https://XXX:7012/CASSupplierWS-WebService-context-root/SupplierServicePort?xsd=1', relative to 'file:/C:/Users/XXX/AppData/Local/Temp/temp9084373454376035251.wsdl'.: java.io.IOException: Server returned HTTP response code: 401 for URL: https://XXX:7012/CASSupplierWS-WebService-context-root/SupplierServicePort?xsd=1
        at org.reficio.ws.builder.core.Wsdl.<init>(Wsdl.java:52)
        at org.reficio.ws.builder.core.Wsdl.parse(Wsdl.java:64)
        at burp.WSDLParser.parseWSDL(WSDLParser.java:75)
        at burp.Worker.doInBackground(Menu.java:101)
        at burp.Worker.doInBackground(Menu.java:74)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: javax.wsdl.WSDLException: WSDLException (at /definitions/types/xsd:schema[2]): faultCode=OTHER_ERROR: An error occurred trying to resolve schema referenced at 'https://XXX:7012/CASSupplierWS-WebService-context-root/SupplierServicePort?xsd=1', relative to 'file:/C:/Users/XXX/AppData/Local/Temp/temp9084373454376035251.wsdl'.: java.io.IOException: Server returned HTTP response code: 401 for URL: https://XXX:7012/CASSupplierWS-WebService-context-root/SupplierServicePort?xsd=1
        at com.ibm.wsdl.xml.WSDLReaderImpl.parseSchema(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.parseSchema(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.parseTypes(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.parseDefinitions(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(Unknown Source)
        at org.reficio.ws.legacy.SoapMessageBuilder.<init>(SoapMessageBuilder.java:98)
        at org.reficio.ws.legacy.SoapLegacyFacade.<init>(SoapLegacyFacade.java:47)
        at org.reficio.ws.builder.core.Wsdl.<init>(Wsdl.java:50)
        ... 10 more
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL:
 https://XXX:7012/CASSupplierWS-WebService-context-root/SupplierServicePort?xsd=1
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at java.net.URL.openStream(Unknown Source)
        at com.ibm.wsdl.util.StringUtils.getContentAsInputStream(Unknown Source)

```
    ... 22 more
```

**Comment by egru** [comment]
Try the latest release from the releases tab.

**Comment by ruiper** [comment]
Yeah, already did that, same problem. The Burp ppl indicated that WSDLER may be making its own HTTP requests. Is that correct? If it were going through the Burp engine instead, it should pick up the ‘Platform Authentication’ settings from there.

I’m doing some testing against a production web service, so I can’t very well ask them to disable the authentication just for testing. Is this issue relatively easy to fix? I notice there are two other issues pending in the q.

Thanks

Rui

**Comment by egru** [comment]
It does make HTTP requests through the wsdl4j library, which is independent of how burp performs requests. I can see if I can modify the request sending functionality to include the basic auth headers.

**Comment by egru** [comment]
I modified the XSD requesting code a bit to include the headers from Burp. So if you authenticate and then parse the WSDL, the Auth header should be include in every further request. The update is in the release section. Let me know if that fixes it.

**Comment by ruiper** [comment]
Eric

Thanks for the amazing turn-around but unfortunately the issue still remains. It does not appear the Authorization header is being sent. Dang.

Rui

**Comment by egru** [comment]
I'll try again with the actual Burp HTTP methods instead of the Java ones to see if it picks up the platform authentication when it's set in Burp.

**Comment by egru** [comment]
Try now. I just updated 2.0.10 again. It seems to working for me.

**Comment by ruiper** [comment]
Eric

Ummm, I have Platform Authentication enabled in Burp (Prof 1.6.39) – Do platform authentication is enabled and set correctly for the target server (checked I can login manually with same account and password). But the issue (401 error persists). 

Any chance that my accessing the WSDL URL on a non-standard port (7012) can have anything to do with this?

Strangely enough if I turn off platform authentication the error becomes ‘org.xml.sax.SAXParseException: White spaces are required between publicid and systemid.’ It appears to be succefully accessing the WSDL file, but trips up elsewhere. I can’t find any reference to publicid and systemid in the WSDL file…  

Sorry for the hassle.

Thanks 

Rui

**Comment by egru** [comment]
The port shouldn't have anything to do with it. My guess is there are some other areas of the libraries I'm using that do some requests themselves. I've tested this doing NTLM Auth with Burp and it worked for me, but I don't have any Basic Auth endpoints to test against. I'll take another look at it tomorrow.

**Comment by egru** [comment]
I updated it again. See if it works this time.

**Comment by ruiper** [comment]
Eric, you are a start. The authentication error is gone. Now I get…Though this is likely an issue with the xsd file, not your code. Unless you can see something really obvious.

Thanks much!

Rui

https://xxx:7012/CASSupplierWS-WebService-context-root/SupplierServicePort?xsd=1:0: error: The document is not a schema@http://www.w3.org/2001/XMLSchema: document element mismatch got definitions@http://schemas.xmlsoap.org/wsdl/

org.reficio.ws.legacy.SchemaUtils.loadSchemaTypes(SchemaUtils.java:115)

org.reficio.ws.legacy.SchemaDefinitionWrapper.loadSchemaTypes(SchemaDefinitionWrapper.java:97)

org.reficio.ws.legacy.SchemaDefinitionWrapper.<init>(SchemaDefinitionWrapper.java:60)

org.reficio.ws.legacy.SoapMessageBuilder.<init>(SoapMessageBuilder.java:99)

org.reficio.ws.legacy.SoapLegacyFacade.<init>(SoapLegacyFacade.java:47)

org.reficio.ws.builder.core.Wsdl.<init>(Wsdl.java:50)

org.reficio.ws.builder.core.Wsdl.parse(Wsdl.java:64)

burp.WSDLParser.parseWSDL(WSDLParser.java:72)

burp.Worker.doInBackground(Menu.java:99)

burp.Worker.doInBackground(Menu.java:72)

javax.swing.SwingWorker$1.call(Unknown Source)

java.util.concurrent.FutureTask.run(Unknown Source)

javax.swing.SwingWorker.run(Unknown Source)

java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

java.lang.Thread.run(Unknown Source)

**Comment by egru** [comment]
I would install the Logger++ extension and see what Wsdler is requesting and see what the responses are. If it's saying the xsd is not a schema it may be some other response coming back.

**Comment by ruiper** [comment]
Eric

All Logger++ shows is the same 4 calls to https://.../...?wsdl , all return HTTP status 200, same length, MIME type XML, though each uses a different JSESSIONID cookie. All requests are using the same Basic authentication as expected.

I am attaching a copy of the XML response in case you can see something there…fyi at minimum xmlns:gcgbcs="http://xxx/Supplier" does not exist.

Rui

<?xml version='1.0' encoding='UTF-8'?>



<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:CASSupplier" xmlns:t="urn:CASSupplier/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:gcgbcs="http://xxx/Supplier" targetNamespace="urn:CASSupplier">
  <types>
    <xsd:schema targetNamespace="urn:CASSupplier/types" elementFormDefault="qualified">/xsd:schema
    xsd:schema
  <xsd:import schemaLocation="https://xxx:7012/CASSupplierWS-WebService-context-root/SupplierServicePort?xsd=1 <https://molson.cas.gov.bc.ca:7012/CASSupplierWS-WebService-context-root/SupplierServicePort?xsd=1> " namespace="http://xxx/Supplier http://xxx/Supplier%22/ "/>
    /xsd:schema
  </types>
  <portType name="SupplierService">
    <operation name="GetSupplier">
  <input message="tns:CAS_SupplierGetRequest"/>
  <output message="tns:CAS_SupplierGetResponse"/>
    </operation>
    <operation name="CreateSupplier">
  <input message="tns:CAS_SupplierCreateRequest"/>
  <output message="tns:CAS_SupplierCreateResponse"/>
    </operation>
    <operation name="UpdateSupplier">
  <input message="tns:CAS_SupplierUpdateRequest"/>
  <output message="tns:CAS_SupplierUpdateResponse"/>
    </operation>
    <operation name="CreateSites">
  <input message="tns:CAS_SitesCreateRequest"/>
  <output message="tns:CAS_SitesCreateResponse"/>
    </operation>
    <operation name="UpdateSites">
  <input message="tns:CAS_SitesUpdateRequest"/>
  <output message="tns:CAS_SitesUpdateResponse"/>
    </operation>
    <operation name="DeactivateSupplier">
  <input message="tns:CAS_SupplierDeactivateRequest"/>
  <output message="tns:CAS_SupplierDeactivateResponse"/>
    </operation>
    <operation name="DeactivateSites">
  <input message="tns:CAS_SupplierSitesDeactivateRequest"/>
  <output message="tns:CAS_SupplierSitesDeactivateResponse"/>
    </operation>
    <operation name="ReactivateSupplier">
  <input message="tns:CAS_SupplierReactivateRequest"/>
  <output message="tns:CAS_SupplierReactivateResponse"/>
    </operation>
    <operation name="ReactivateSites">
  <input message="tns:CAS_SupplierSitesReactivateRequest"/>
  <output message="tns:CAS_SupplierSitesReactivateResponse"/>
    </operation>
  </portType>
  <message name="CAS_SupplierGetRequest">
    <part name="supplier" element="gcgbcs:GetSupplierRequest"/>
  </message>
  <message name="CAS_SupplierGetResponse">
    <part name="supplierResponse" element="gcgbcs:GetSupplierResponse"/>
  </message>
  <message name="CAS_SupplierCreateRequest">
    <part name="supplier" element="gcgbcs:CreateSupplierRequest"/>
  </message>
  <message name="CAS_SupplierCreateResponse">
    <part name="supplierResponse" element="gcgbcs:CreateSupplierResponse"/>
  </message>
  <message name="CAS_SupplierUpdateRequest">
    <part name="supplier" element="gcgbcs:UpdateSupplierRequest"/>
  </message>
  <message name="CAS_SupplierUpdateResponse">
    <part name="supplierResponse" element="gcgbcs:UpdateSupplierResponse"/>
  </message>
  <message name="CAS_SitesCreateRequest">
    <part name="sites" element="gcgbcs:CreateSitesRequest"/>
  </message>
  <message name="CAS_SitesCreateResponse">
    <part name="sitesResponse" element="gcgbcs:CreateSitesResponse"/>
  </message>
  <message name="CAS_SitesUpdateRequest">
    <part name="sites" element="gcgbcs:UpdateSitesRequest"/>
  </message>
  <message name="CAS_SitesUpdateResponse">
    <part name="sitesResponse" element="gcgbcs:UpdateSitesResponse"/>
  </message>
  <message name="CAS_SupplierDeactivateRequest">
    <part name="supplierRequest" element="gcgbcs:DeactivateSupplierRequest"/>
  </message>
  <message name="CAS_SupplierDeactivateResponse">
    <part name="supplierResponse" element="gcgbcs:DeactivateSupplierResponse"/>
  </message>
  <message name="CAS_SupplierSitesDeactivateRequest">
    <part name="sitesRequest" element="gcgbcs:DeactivateSitesRequest"/>
  </message>
  <message name="CAS_SupplierSitesDeactivateResponse">
    <part name="sitesResponse" element="gcgbcs:DeactivateSitesResponse"/>
  </message>
  <message name="CAS_SupplierReactivateRequest">
    <part name="supplierRequest" element="gcgbcs:ReactivateSupplierRequest"/>
  </message>
  <message name="CAS_SupplierReactivateResponse">
    <part name="supplierResponse" element="gcgbcs:ReactivateSupplierResponse"/>
  </message>
  <message name="CAS_SupplierSitesReactivateRequest">
    <part name="sitesRequest" element="gcgbcs:ReactivateSitesRequest"/>
  </message>
  <message name="CAS_SupplierSitesReactivateResponse">
    <part name="sitesResponse" element="gcgbcs:ReactivateSitesResponse"/>
  </message>
  <binding name="SupplierServiceSOAP12Binding" type="tns:SupplierService">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http <http://schemas.xmlsoap.org/soap/http%22/> "/>
    <operation name="GetSupplier">
  <soap12:operation style="document" soapAction="urn:CASSupplier/GetSupplier"/>
  <input>
    <soap12:body use="literal"/>
  </input>
  <output>
    <soap12:body use="literal"/>
  </output>
    </operation>
    <operation name="CreateSupplier">
  <soap12:operation style="document" soapAction="urn:CASSupplier/CreateSupplier"/>
  <input>
    <soap12:body use="literal"/>
  </input>
  <output>
    <soap12:body use="literal"/>
  </output>
    </operation>
    <operation name="UpdateSupplier">
  <soap12:operation style="document" soapAction="urn:CASSupplier/UpdateSupplier"/>
  <input>
    <soap12:body use="literal"/>
  </input>
  <output>
    <soap12:body use="literal"/>
  </output>
    </operation>
    <operation name="CreateSites">
  <soap12:operation style="document" soapAction="urn:CASSupplier/CreateSites"/>
  <input>
    <soap12:body use="literal"/>
  </input>
  <output>
    <soap12:body use="literal"/>
  </output>
    </operation>
    <operation name="UpdateSites">
  <soap12:operation style="document" soapAction="urn:CASSupplier/UpdateSites"/>
  <input>
    <soap12:body use="literal"/>
  </input>
  <output>
    <soap12:body use="literal"/>
  </output>
    </operation>
    <operation name="DeactivateSupplier">
  <soap12:operation style="document" soapAction="urn:CASSupplier/DeactivateSupplier"/>
  <input>
    <soap12:body use="literal"/>
  </input>
  <output>
    <soap12:body use="literal"/>
  </output>
    </operation>
    <operation name="ReactivateSupplier">
  <soap12:operation style="document" soapAction="urn:CASSupplier/ReactivateSupplier"/>
  <input>
    <soap12:body use="literal"/>
  </input>
  <output>
    <soap12:body use="literal"/>
  </output>
    </operation>
    <operation name="DeactivateSites">
  <soap12:operation style="document" soapAction="urn:CASSupplier/DeactivateSites"/>
  <input>
    <soap12:body use="literal"/>
  </input>
  <output>
    <soap12:body use="literal"/>
  </output>
    </operation>
    <operation name="ReactivateSites">
  <soap12:operation style="document" soapAction="urn:CASSupplier/ReactivateSites"/>
  <input>
    <soap12:body use="literal"/>
  </input>
  <output>
    <soap12:body use="literal"/>
  </output>
    </operation>
  </binding>
  <service name="SupplierService">
    <port name="SupplierServicePort" binding="tns:SupplierServiceSOAP12Binding">
  <soap12:address location="https://xxx:7012/CASSupplierWS-WebService-context-root/SupplierServicePort <https://xxx:7012/CASSupplierWS-WebService-context-root/SupplierServicePort%22/> "/>
    </port>
  </service>
</definitions>

**Comment by ruiper** [comment]
Eric?

Revisiting this I find that the latest version of wsdler fails in the same way (https://xxx:7012/CASSupplierWS-WebService-context-root/SupplierServicePort?xsd=1:0: error: The document is not a schema@http://www.w3.org/2001/XMLSchema: document element mismatch got definitions@http://schemas.xmlsoap.org/wsdl/) even for services where previous versions actually worked. If I go back to version 9 of wsdler these other WSDL files are parsed correctly. So, whatever you did in version 10  to fix the basic authentication issues screwed up the actual parsing. Others should be having the same issues with version 10, since it fails on the WSDL files where it previously worked.

Thanks 

From: Rui Pereira (Shaw1) [mailto:ruiper@shaw.ca] 
Sent: Saturday, April 09, 2016 1:09 PM
To: 'NetSPI/Wsdler'; 'NetSPI/Wsdler'
Subject: RE: [NetSPI/Wsdler] Fails (HTTP 401) if Basic Authentication required to access URL's in XSD (#4)

Eric

All Logger++ shows is the same 4 calls to https://.../...?wsdl , all return HTTP status 200, same length, MIME type XML, though each uses a different JSESSIONID cookie. All requests are using the same Basic authentication as expected.

I am attaching a copy of the XML response in case you can see something there…fyi at minimum xmlns:gcgbcs="http://xxx/Supplier" does not exist.

Rui

<snipped>

**Comment by egru** [comment]
I think I figured it out. Try the latest one I just uploaded.

**Comment by ruiper** [comment]
Yessir, now it works for all of them. You’re a star.

R

**Comment by egru** [comment]
Good to hear.
