### ISSUE TITLE
BApp was revoked

### ISSUE THREAD

**Issue by syntacticvexation** [NetSPI/Wsdler#6]
I've been attempting to install this BApp but I'm getting a "BApp was revoked" message and I can no longer install Wsdler.  Will it be coming back to the BApp store?

Thanks.

**Comment by egru** [comment]
Yeah, there was an XXE vulnerability in it. It's fixed now in the repo and you can download it from the releases and manually load the jar in Burp. It should be back in the BApp store next week.
